"""rename source_number to source_question_number

Revision ID: 5837e96d85fd
Revises: 087545e17ff3
Create Date: 2026-04-13 15:17:41.821775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5837e96d85fd'
down_revision: Union[str, Sequence[str], None] = '087545e17ff3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('source_question_number', sa.String(), nullable=True))
    op.drop_column('questions', 'source_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('source_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('questions', 'source_question_number')
    # ### end Alembic commands ###
