"""Initial Schema

Revision ID: 860b94e6712a
Revises: 
Create Date: 2026-04-08 09:26:52.599754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '860b94e6712a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('path_type', sa.Enum('structured', 'flexible', name='pathtype'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_categories_name')
    )
    op.create_table('course_path_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('node_type', sa.Enum('grade', 'subject', 'course', name='nodetype'), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('owner_type', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['course_path_nodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'node_type', 'category_id', 'parent_id', name='uq_course_path_nodes')
    )
    op.create_table('exam_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_path_node_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('mode', sa.Enum('static', 'dynamic', 'custom', name='exammode'), nullable=False),
    sa.Column('ruleset', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('passing_score', sa.Float(), nullable=True),
    sa.Column('owner_type', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.CheckConstraint('duration_minutes IS NULL OR duration_minutes > 0', name='ck_exam_templates_duration_positive'),
    sa.CheckConstraint('passing_score IS NULL OR (passing_score >= 0.0 AND passing_score <= 1.0)', name='ck_exam_templates_passing_score_range'),
    sa.ForeignKeyConstraint(['course_path_node_id'], ['course_path_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('course_path_node_id', sa.UUID(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('owner_type', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['course_path_node_id'], ['course_path_nodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title', 'course_path_node_id', name='uq_topics_title_node')
    )
    op.create_table('exam_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('exam_template_id', sa.UUID(), nullable=True),
    sa.Column('course_path_node_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.Enum('static', 'dynamic', 'custom', name='exammode'), nullable=False),
    sa.Column('ruleset', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'ongoing', 'completed', 'failed', name='examstatus'), nullable=True),
    sa.ForeignKeyConstraint(['course_path_node_id'], ['course_path_nodes.id'], ),
    sa.ForeignKeyConstraint(['exam_template_id'], ['exam_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paragraph_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=True),
    sa.Column('question_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('paragraph_type', sa.Enum('reading_comprehension', 'case_study', 'data_interpretation', name='paragraphtype'), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_text', sa.String(), nullable=False),
    sa.Column('question_type', sa.Enum('single_choice', 'multiple_choice', 'true_false', 'fill_in_the_blank', 'essay', 'paragraph', name='questiontype'), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correct_answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='difficultylevel'), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('topic_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic_contents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('content_type', sa.Enum('video', 'pdf', 'text', 'question', 'question_answer', name='contenttype'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', 'title', name='uq_topic_contents_topic_title')
    )
    op.create_table('answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('selected_options', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('text_answer', sa.String(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['exam_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam_session_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exam_session_id', sa.UUID(), nullable=True),
    sa.Column('question_id', sa.UUID(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('earned_points', sa.Float(), nullable=True),
    sa.Column('user_answer', sa.String(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['exam_session_id'], ['exam_sessions.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam_template_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exam_template_id', sa.UUID(), nullable=True),
    sa.Column('question_id', sa.UUID(), nullable=True),
    sa.Column('paragraph_question_id', sa.UUID(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exam_template_id'], ['exam_templates.id'], ),
    sa.ForeignKeyConstraint(['paragraph_question_id'], ['paragraph_questions.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exam_template_questions')
    op.drop_table('exam_session_questions')
    op.drop_table('answers')
    op.drop_table('topic_contents')
    op.drop_table('questions')
    op.drop_table('paragraph_questions')
    op.drop_table('exam_sessions')
    op.drop_table('topics')
    op.drop_table('exam_templates')
    op.drop_table('course_path_nodes')
    op.drop_table('categories')
    # ### end Alembic commands ###
